In [1]:
from summarynb import show, image, csv, indexed_csv, chunks, plaintext, empty

%load_ext autoreload
%autoreload 2

```
> summarynb install
installed

> summarynb mark Example.ipynb
Registered notebook for autorun. Make sure git pre-commit hook is installed by running: summarynb install

> summarynb list
        filename  exists
0  Example.ipynb    True

# test run
> summarynb run
Running summary notebooks. Skip this with --no-verify
Example.ipynb
ran hook

> git commit ...
```

# Basics: single image

In [2]:
show("tests/data/run_1.png")

# Make tables

In [3]:
show([["tests/data/run_1.png", "tests/data/run_1.csv"]])

In [4]:
show(
    [
        ["tests/data/run_1.png", "tests/data/run_1.csv"],
        ["tests/data/run_2.png", "tests/data/run_2.csv"],
    ],
    headers=["Images", "Tables"],
)

# Helpers

In [5]:
show(csv("tests/data/run_summary.tsv", sep="\t", index_col=0))

In [6]:
show(
    [
        ["tests/data/run_1.png", indexed_csv("tests/data/run_1.csv")],
        [image("tests/data/run_2.png"), indexed_csv("tests/data/run_2.csv")],
    ],
    max_width=1200,
)

In [7]:
show(
    chunks(
        entries=[
            [
                image("tests/data/run_%d.png" % (i + 1)),
                indexed_csv("tests/data/run_%d.csv" % (i + 1)),
            ]
            for i in range(16)
        ],
        shape=4,
    )
)

# Other functionality

In [8]:
show([plaintext("Plain text"), empty(), "tests/data/test.txt"], max_width=300)